name: Terraform CI/CD Automation

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}

      TF_VAR_github_owner: ${{ github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # IMPORTANT: Restore previous Terraform state (if exists)
      - name: Download Terraform state
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: terraform
        continue-on-error: true

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      # IMPORTANT: Save Terraform state for future runs
      - name: Upload Terraform state
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
